"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
from . import itinerary_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class ItineraryServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    GetVersion: grpc.UnaryUnaryMultiCallable[
        itinerary_pb2.GetVersionRequest,
        itinerary_pb2.GetVersionResponse,
    ]

class ItineraryServiceAsyncStub:
    GetVersion: grpc.aio.UnaryUnaryMultiCallable[
        itinerary_pb2.GetVersionRequest,
        itinerary_pb2.GetVersionResponse,
    ]

class ItineraryServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetVersion(
        self,
        request: itinerary_pb2.GetVersionRequest,
        context: _ServicerContext,
    ) -> typing.Union[itinerary_pb2.GetVersionResponse, collections.abc.Awaitable[itinerary_pb2.GetVersionResponse]]: ...

def add_ItineraryServiceServicer_to_server(servicer: ItineraryServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
